### ISSUE TITLE
关于旋转估计R的计算

### ISSUE THREAD

**Issue by Cauchyck** [yokinglou/CRIN#1]
您好，首先对你们的工作表示感谢。在论文中关于公式（6），即R* = B_t*B_s.T我有一点疑问。从论文中可以得知如何计算B*，但在计算R*时似乎并不需要anchor point是源点云和目标点云中同一个点。只需其具有代表性即可。请问是否是这样？

PS：希望能代码能早日开源，以便进一步学习！感谢🙏！！！

**Comment by yokinglou** [comment]
Hi, 
计算R*的时候，代表性的点针对单个物体是需要相对稳定的，目的是尽可能使用源和目标点云中的同一个点。但由于噪声等原因，旋转前后预测的代表点会存在一定的偏差。
我们会尽快处理的，感谢您的关注～

**Comment by Cauchyck** [comment]
好的，感谢您的回复。
